name: Build from source
on: [push]
jobs:
  Build-from-source:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        bash build.sh

    - name: Test
      run: |
        ### We need to run export again if we move to the different step ###
        export PATH="$HOME/miniconda/bin:$PATH"
        export PYTHONPATH=$HOME/faiss/build/faiss/python/build/lib:$PYTHONPATH

        cd $HOME/faiss

        echo "##### Check ldd of .so #####"
        ldd build/faiss/libfaiss_avx2.so

        echo "##### Run c++ test #####"        
        make -C build -j demo_ivfpq_indexing
        ./build/demos/demo_ivfpq_indexing

        echo "##### Run python test #####"        
        cd
        python -c "import faiss, numpy; err = faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 10).astype('float32')); print(err)"

        echo "##### AVX2 is activated or not #####"
        LD_DEBUG=libs python -c "import faiss" 2>&1 | grep libfaiss_avx2.so
