name: Build from source
on: [push]
jobs:
  Build-from-source:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install by apt
      run: |
        sudo apt install -y build-essential swig
        sudo apt install -y intel-mkl
        sudo snap install cmake --classic

    - name: Install miniconda
      run: |
        cd $HOME
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
        bash ~/miniconda.sh -b -p $HOME/miniconda
        echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $HOME/.bashrc
        source $HOME/.bashrc
        conda update conda --yes
        conda update --all --yes
        conda install numpy --yes
  
    - name: Install faiss
      run: |
        cd $HOME
        git clone https://github.com/facebookresearch/faiss.git
        cd faiss
        
        cmake -B build \
            -DBUILD_SHARED_LIBS=ON \
            -DBUILD_TESTING=ON \
            -DFAISS_OPT_LEVEL=avx2 \
            -DFAISS_ENABLE_GPU=OFF \
            -DFAISS_ENABLE_PYTHON=$HOME/miniconda/bin/python \
            -DCMAKE_BUILD_TYPE=Release .
        
        make -C build -j faiss faiss_avx2
        
        make -C build -j swigfaiss swigfaiss_avx2
        
        (cd build/faiss/python && python setup.py install)
        
        echo 'export PYTHONPATH=$HOME/faiss/build/faiss/python/build/lib:$PYTHONPATH' >> $HOME/.bashrc
        source $HOME/.bashrc



    - name: Test
      run: |
        cd $HOME/faiss
        
        ldd build/faiss/libfaiss_avx2.so
        
        make -C build demo_ivfpq_indexing
        ./build/demos/demo_ivfpq_indexing

        cd
        python -c "import faiss, numpy; err = faiss.Kmeans(10, 20).train(numpy.random.rand(1000, 10).astype('float32')); print(err)"

        LD_DEBUG=libs python -c "import faiss" 2>&1 | grep libfaiss_avx2.so
